### ISSUE TITLE
404链接

### ISSUE THREAD

**Issue by xbox1994** [Relph1119/mysql-learning#2]
https://relph1119.github.io/mysql-learning-notes/#/mysql/09-%E5%AD%98%E6%94%BE%E9%A1%B5%E9%9D%A2%E7%9A%84%E5%A4%A7%E6%B1%A0%E5%AD%90-InnoDB%E7%9A%84%E8%A1%A8%E7%A9%BA%E9%97%B4

**Comment by JeanChrist** [comment]
https://relph1119.github.io/mysql-learning-notes/#/mysql/09-%E5%AD%98%E6%94%BE%E9%A1%B5%E7%9A%84%E5%A4%A7%E6%B1%A0%E5%AD%90-InnoDB%E7%9A%84%E8%A1%A8%E7%A9%BA%E9%97%B4

看了一下md文件名少了一个字，这个链接是ok的。
