### ISSUE TITLE
页面渲染出错

### ISSUE THREAD

**Issue by patrhez** [Relph1119/mysql-learning#4]
你好！这个页面存在缺少图片和排版混乱的问题。

[第12章 谁最便宜就选谁-MySQL基于成本的优化](https://relph1119.github.io/mysql-learning-notes/#/mysql/12-%E8%B0%81%E6%9C%80%E4%BE%BF%E5%AE%9C%E5%B0%B1%E9%80%89%E8%B0%81-MySQL%E5%9F%BA%E4%BA%8E%E6%88%90%E6%9C%AC%E7%9A%84%E4%BC%98%E5%8C%96?id=%e7%ac%ac12%e7%ab%a0-%e8%b0%81%e6%9c%80%e4%be%bf%e5%ae%9c%e5%b0%b1%e9%80%89%e8%b0%81-mysql%e5%9f%ba%e4%ba%8e%e6%88%90%e6%9c%ac%e7%9a%84%e4%bc%98%e5%8c%96)

[第13章 兵马未动，粮草先行-InnoDB统计数据是如何收集的](https://relph1119.github.io/mysql-learning-notes/#/mysql/13-%E5%85%B5%E9%A9%AC%E6%9C%AA%E5%8A%A8%EF%BC%8C%E7%B2%AE%E8%8D%89%E5%85%88%E8%A1%8C-InnoDB%E7%BB%9F%E8%AE%A1%E6%95%B0%E6%8D%AE%E6%98%AF%E5%A6%82%E4%BD%95%E6%94%B6%E9%9B%86%E7%9A%84?id=%e7%ac%ac13%e7%ab%a0-%e5%85%b5%e9%a9%ac%e6%9c%aa%e5%8a%a8%ef%bc%8c%e7%b2%ae%e8%8d%89%e5%85%88%e8%a1%8c-innodb%e7%bb%9f%e8%ae%a1%e6%95%b0%e6%8d%ae%e6%98%af%e5%a6%82%e4%bd%95%e6%94%b6%e9%9b%86%e7%9a%84)

@Relph1119

**Comment by Relph1119** [comment]
已解决，顺便把其他页面的渲染问题也已修复，谢谢了
