### ISSUE TITLE
第25章缩进排版错误

### ISSUE THREAD

**Issue by patrhez** [Relph1119/mysql-learning#5]
你好，https://relph1119.github.io/mysql-learning-notes/#/mysql/25-%E5%B7%A5%E4%BD%9C%E9%9D%A2%E8%AF%95%E8%80%81%E5%A4%A7%E9%9A%BE-%E9%94%81?id=innodb%e4%b8%ad%e7%9a%84%e8%a1%8c%e7%ba%a7%e9%94%81

这里出现了一处排版错误，

InnoDB中的行级锁

这一标题缩进出了问题。:)

@Relph1119

**Comment by Relph1119** [comment]
已解决，谢谢了
